<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('productos')->insert([
            [
                'nompro' => 'Pulsera de Cuero',
                'descpro' => 'Pulsera artesanal hecha de cuero genuino.',
                'prepro' => 29.99,
                'stock_disponible' => 50,
                'stock_minimo' => 5,
                'estpro' => 'activo',
                'certipro' => 'Certificado de Autenticidad',
                'imgpro' => 'pulsera_de_cuero.jpeg',
                'codcatg' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Collar de Plata',
                'descpro' => 'Collar elegante de plata 925 con diseño exclusivo.',
                'prepro' => 75.50,
                'stock_disponible' => 30,
                'stock_minimo' => 3,
                'estpro' => 'activo',
                'certipro' => 'Certificado de Plata',
                'imgpro' => 'collar_de_plata.jpeg',
                'codcatg' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Aretes de Perlas',
                'descpro' => 'Aretes delicados con perlas naturales.',
                'prepro' => 45.00,
                'stock_disponible' => 20,
                'stock_minimo' => 2,
                'estpro' => 'activo',
                'certipro' => 'Certificado de Calidad',
                'imgpro' => 'arete_de_perlas.jpeg',
                'codcatg' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Llaveros Personalizados',
                'descpro' => 'Llaveros con grabado personalizado en metal.',
                'prepro' => 15.99,
                'stock_disponible' => 100,
                'stock_minimo' => 10,
                'estpro' => 'activo',
                'certipro' => 'Garantía de Calidad',
                'imgpro' => 'llaveros_personalizados.jpeg',
                'codcatg' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Pulsera Trenzada',
                'descpro' => 'Pulsera trenzada hecha a mano con hilo de colores.',
                'prepro' => 12.50,
                'stock_disponible' => 70,
                'stock_minimo' => 5,
                'estpro' => 'borrador',
                'certipro' => 'Certificado de Artesanía',
                'imgpro' => 'pulsera_trenzada.jpeg',
                'codcatg' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Collar de Madera',
                'descpro' => 'Collar artesanal hecho con piezas de madera natural.',
                'prepro' => 40.00,
                'stock_disponible' => 40,
                'stock_minimo' => 4,
                'estpro' => 'inactivo',
                'certipro' => 'Certificado Eco-Friendly',
                'imgpro' => 'collar_de_madera.jpg',
                'codcatg' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Anillo Ajustable',
                'descpro' => 'Anillo artesanal ajustable hecho de acero inoxidable.',
                'prepro' => 22.00,
                'stock_disponible' => 35,
                'stock_minimo' => 3,
                'estpro' => 'activo',
                'certipro' => 'Certificado de Calidad',
                'imgpro' => 'anillo_ajustable.jpeg',
                'codcatg' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Pendientes de Madera',
                'descpro' => 'Pendientes ligeros hechos de madera reciclada.',
                'prepro' => 18.75,
                'stock_disponible' => 60,
                'stock_minimo' => 6,
                'estpro' => 'activo',
                'certipro' => 'Certificado Eco-Friendly',
                'imgpro' => 'pendientes_de_madera.jpeg',
                'codcatg' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Llavero de Cuero',
                'descpro' => 'Llavero hecho a mano con cuero genuino.',
                'prepro' => 10.50,
                'stock_disponible' => 80,
                'stock_minimo' => 8,
                'estpro' => 'borrador',
                'certipro' => 'Garantía de Calidad',
                'imgpro' => 'llavero_de_cuero.jpeg',
                'codcatg' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Pulsera Minimalista',
                'descpro' => 'Pulsera sencilla con diseño minimalista y elegante.',
                'prepro' => 14.99,
                'stock_disponible' => 55,
                'stock_minimo' => 5,
                'estpro' => 'activo',
                'certipro' => 'Certificado de Autenticidad',
                'imgpro' => 'pulsera_minimalista.jpeg',
                'codcatg' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Collar de Cuentas',
                'descpro' => 'Collar colorido hecho con cuentas de vidrio artesanal.',
                'prepro' => 27.80,
                'stock_disponible' => 45,
                'stock_minimo' => 4,
                'estpro' => 'inactivo',
                'certipro' => 'Certificado de Artesanía',
                'imgpro' => 'collar_de_cuentas.jpeg',
                'codcatg' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nompro' => 'Llavero Metálico',
                'descpro' => 'Llavero resistente hecho de metal reciclado.',
                'prepro' => 13.25,
                'stock_disponible' => 90,
                'stock_minimo' => 9,
                'estpro' => 'activo',
                'certipro' => 'Garantía de Calidad',
                'imgpro' => 'llavero_metalico.jpg',
                'codcatg' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
